export const keywords = [
    'color',
    'colors',
    'color scheme',
    'scheme color',
    'color schemes',
    'color theme',
    'color themes',
    'theme color',
    'theme colors',
    'color palette',
    'color palettes',
    'color combinations',
    'palettes',
    'hex color wheel',
    'pastel color palette',
    'color wheel',
    'color combination',
    'color pallete',
    'color panels',
    'color names',
    'web color schemes',
    'color wheel generator',
    'extract color palette from image',
    'random color palette generator',
    'color schemes generator',
    'ui color palette generator',
    'pretty colors',
    'vintage color',
    'color palette from image'
].join(',')
export const description = 'collect your favorite page theme colors, easily save, edit and use.'
